### PR TITLE
free: Fix incorrect `CachUse` value with `--line --wide`

### PR DESCRIPTION
**Pull request by MCredbear**
#89

### CODE REVIEW

**Comment by Krysztal112233** [comment]
Thank for your contribution but I think you can create branch from `upstream/main` follows our step, then create modification on it and made a pr last.

Your commits seems no problem but...so mess, it contains content of two pr.

**Comment by Krysztal112233** [comment]
And please take a look about this comment, I think it will be much helpful to you
 https://github.com/uutils/procps/pull/172#pullrequestreview-2229440778

**Comment by Krysztal112233** [comment]
And please take a look about this comment, I think it will be much helpful to you
 https://github.com/uutils/procps/pull/172#pullrequestreview-2229440778

**Comment by MCredbear** [comment]
Sry, but what should I do now? Close this and reopen a PR?

**Comment by Krysztal112233** [comment]
> Sry, but what should I do now? Close this and reopen a PR?

Yeah I think you retarget your commit on `upstream/main` would be better.

**Pull request closed without merging**
