### PR TITLE
Fix output formatting for free

### PR DESCRIPTION
**Pull request by claudex**
The GNU free is using 11 chars wide for number, not 12. This was also causing a misalignment of the numbers with the title.

The source for the 11 chars wide: https://gitlab.com/procps-ng/procps/-/blob/master/src/free.c?ref_type=heads#L336

### CODE REVIEW

**Comment by sylvestre** [comment]
please don't look at the source of the GNU implementation. it is GPL code and incompatible with this license.

**Comment by sylvestre** [comment]
also, could you please add a test https://github.com/uutils/procps/blob/main/tests/by-util/test_free.rs to make sure we don't regress?
thanks

**Comment by claudex** [comment]
I've added the tests, tell me if you think I should test more.

**Comment by claudex** [comment]
Sorry, I forgot to run `cargo fmt`

**Comment by sylvestre** [comment]
thanks

**Pull request merged**
